name: medi
description: "MediAI is a Flutter application designed to provide intelligent healthcare solutions using modern mobile technologies."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio:
  flutter_easyloading:
  flutter_screenutil:
  google_fonts:
  logger:
  connectivity_plus: ^6.1.4
  url_launcher:
  shared_value:
  intl:
  any_image_view: ^1.6.0
  easy_debounce:
  water_drop_nav_bar:
  font_awesome_flutter:
  omni_datetime_picker:
  delayed_display:
  flutter_spinkit:
  skeletonizer:
  dropdown_search: ^6.0.2
  animated_bottom_navigation_bar: ^1.4.0
  google_maps_places_autocomplete_widgets: ^1.3.3
  google_maps_flutter:
  image_picker: ^1.1.2
  clay_containers: ^0.3.4
  country_code_picker: ^3.3.0
  flutter_dotenv:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/categoryIcons/
    - assets/dashboardIcons/
    - assets/dashboardIcons/h/
    - assets/dashboardIcons/p/
    - assets/image/
    - assets/onboarding/
    - assets/register/
    - .env


